spring:
  application:
    name: payment-system
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:adm}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.example.payment: DEBUG
    org.springframework: INFO